stages:
  - test

linter:
  stage: test
  image: node:20.11-alpine
  script:
    - yarn --frozen-lockfile
    - yarn run lint

integration tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.42.1-jammy
  script:
    - yarn --frozen-lockfile
    - npx playwright install chromium --with-deps
    - yarn run test:integration