stages:
  - test

linter:
  stage: test
  script:
    - docker build -t estimace-fe-linter:latest -f ./Dockerfile.linter .
    - docker rm -f estimace-fe-linter
    - docker run --name estimace-fe-linter estimace-fe-linter:latest
    - docker rm -f estimace-fe-linter

integration tests:
  stage: test
  script:
    - docker build -t estimace-fe-integration:latest -f ./Dockerfile.test .
    - docker rm -f estimace-fe-integration
    - docker run --name estimace-fe-integration estimace-fe-integration:latest
    - docker rm -f estimace-fe-integration