FROM node:18-alpine AS base

# Install dependencies only when needed
FROM base AS app-deps
WORKDIR /opt/app

COPY package.json ./
COPY yarn.lock ./
RUN yarn --frozen-lockfile

# Rebuild the source code only when needed
FROM app-deps
WORKDIR /opt/app
COPY --from=app-deps /opt/app/node_modules ./node_modules
COPY . .

CMD ["yarn", "run", "lint"]